[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Steven Bias <bias_stevn@hotmail.fr>"]

edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
